// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel_Agency_Project.Data;

#nullable disable

namespace Travel_Agency_Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240629145036_CreateDB")]
    partial class CreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Travel_Agency_Project.Models.Transportation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Transportations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Car"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Plane"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Bike"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Bus"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
